# this file generated by script/generate pickle [paths] [email]
#
# Make sure that you are loading your factory of choice in your cucumber environment
#
# For machinist add: features/support/machinist.rb
#
#    require 'machinist/active_record' # or your chosen adaptor
#    require File.dirname(__FILE__) + '/../../spec/blueprints' # or wherever your blueprints are
#    Before { Sham.reset } # to reset Sham's seed between scenarios so each run has same random sequences
#
# For FactoryGirl add: features/support/factory_girl.rb
#
#    require 'factory_girl'
#    require File.dirname(__FILE__) + '/../../spec/factories' # or wherever your factories are
#
# You may also need to add gem dependencies on your factory of choice in <tt>config/environments/cucumber.rb</tt>

require 'pickle/world'
# Example of configuring pickle:

Pickle.configure do |config|
  config.adapters = [:factory_girl]
  config.map 'I', 'myself', 'me', 'my', :to => 'user: "me"'
end

require 'pickle/path/world'
require 'pickle/email/world'


# Monkeypatch for subdomain support?
# module Pickle
#   module Path
#     def pickle_path_for_resources_action_segment(resources, action, segment)
#       action.blank? or action = action.downcase.gsub(' ','_')
#       segment.blank? or segment = segment.downcase.gsub(' ','_')
#       resource_names = resources.map{|s| s.is_a?(Symbol) ? s.to_s : s.class.name.underscore}.join("_")
#       models = resources.reject{|s| s.is_a?(Symbol)}
#       parts = [action, resource_names, segment].reject(&:blank?)
#       send("#{parts.join('_')}_url", *models) rescue nil
#     end
#   end
# end
